name: Cache CC65
description: Caches CC65 and builds it from source if missing
inputs:
  cc65Ref:
    description: "CC65 Git Ref (used to checkout a fixed version)"
    required: false
    default: "18ae09f6821b3ed15121220100023b70ae393e30"
  cc65Path:
    description: "CC65 path to cache"
    required: false
    default: ${{ github.workspace }}/opt/cc65
  
run:
  using: "composite"
  steps:
      # Cache CC65
      - uses: actions/cache@v2
        id: cache_cc65
        with:
          path: ${{ inputs.cc65Path }}
          key: ${{ runner.os }}-cc65-${{ inputs.cc65Ref }}
      # Checkout CC65
      - uses: actions/checkout@v2
        if: steps.cache_cc65.outputs.cache-hit != 'true'
        with:
          repository: cc65/cc65
          ref: ${{ inputs.cc65Ref }}
          path: './cc65'
      # Build CC65
      - if: steps.cache_cc65.outputs.cache-hit != 'true'
        run: |
          cd cc65
          PREFIX=${{ inputs.cc65Path }}/opt/cc65 make
          PREFIX=${{ inputs.cc65Path }}/opt/cc65 make install