name: Cache SDL
run:
  using: "composite"
  steps:
    # Cache SDL2
    - uses: actions/cache@v2
      id: cache_sdl
      with:
        path: |
          ${{ github.workspace }}/build/_deps
          ${{ github.workspace }}/example/build/_deps
        key: ${{ runner.os }}-sdl${{ hashFiles('cmake/buildSDL2.cmake') }}
