name: Cache SDL
description: Caches SDL2 from the build output directories
run:
  using: "composite"
  steps:
    # Cache SDL2
    - uses: actions/cache@v2
      id: cache_sdl
      with:
        path: |
          ${{ env.GITHUB_WORKSPACE }}/build/_deps
          ${{ env.GITHUB_WORKSPACE }}/example/build/_deps
        key: ${{ env.MATRIX_OS }}-sdl${{ hashFiles('cmake/buildSDL2.cmake') }}
