name: Cache FamiStudio
description: Caches FamiStudio and runtime deps (and installs if missing)
inputs:
  fsBin:
    description: "URL path to download FamiStudio Binary from"
    required: true
  fsVersion:
    description: "FS Version (used as cache key)"
    required: false
    default: "3.2.2"
  fsPath:
    description: "Path to install FS to"
    required: false
    default: ${{ github.workspace }}/opt/famistudio
  gtkVersion:
    description: "GTK Version (Linux Only)"
    required: false
    default: "2.12.40-2"
runs:
  using: "composite"
  steps:
    # Cache Famistudio
    - uses: actions/cache@v2
      id: cache_famistudio
      with:
        path: ${{ github.workspace }}/opt/famistudio
        key: ${{ runner.os }}-fami${{ inputs.fsVersion }}
    # Download Famistudio
    - if: steps.cache_famistudio.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ github.workspace }}/opt/famistudio
        wget https://github.com/BleuBleu/FamiStudio/releases/download/${{ inputs.fsBin }} -O famistudio.zip
        unzip famistudio.zip -d ${{ github.workspace }}/opt/famistudio
    # Cache GTK2-Sharp (Linux)
    - uses: actions/cache@v2
      if: matrix.os == 'ubuntu-latest'
      id: cache_gtk
      with:
        path: ${{ github.workspace }}/opt/gtk-sharp2
        key: ${{ runner.os }}-gtk${{ inputs.gtkVersion }}
    # Install GTK2-Sharp (Linux)
    - if: matrix.os == 'ubuntu-latest'
      env:
        CACHE_HIT: ${{steps.cache_gtk.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == 'true' ]]; then
          sudo cp -rf ${{ github.workspace }}/opt/gtk-sharp2/* /
        else
          sudo apt-get install --yes gtk-sharp2="${{ inputs.gtkVersion }}"
          mkdir -p ${{ github.workspace }}/opt/gtk-sharp2/
          sudo dpkg -L gtk-sharp2 | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ${{ github.workspace }}/opt/gtk-sharp2/
        fi
