name: Cache FamiStudio
description: Caches FamiStudio and runtime deps (and installs if missing)
inputs:
  fsBin:
    description: "URL path to download FamiStudio Binary from"
    required: true
  fsVersion:
    description: "FS Version (used as cache key)"
    required: false
    default: "3.2.2"
  fsPath:
    description: "Path to install FS to"
    required: false
    default: ${{ github.workspace }}/opt/famistudio
  gtkVersion:
    description: "GTK Version (Linux Only)"
    required: false
    default: "2.12.40-3"
runs:
  using: "composite"
  steps:
    # Cache Famistudio
    - uses: actions/cache@v2
      id: cache_famistudio
      with:
        path: ${{ github.workspace }}/opt/famistudio
        key: ${{ runner.os }}-fami${{ inputs.fsVersion }}-action-${{ hashFiles('.github/actions/cache_famistudio/*') }}
    # Download Famistudio
    - if: steps.cache_famistudio.outputs.cache-hit != 'true'
      run: |
        New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/opt/famistudio
        Invoke-WebRequest https://github.com/BleuBleu/FamiStudio/releases/download/${{ inputs.fsBin }} -OutFile famistudio.zip
        Expand-Archive -LiteralPath famistudio.zip -DestinationPath ${{ github.workspace }}/opt/famistudio
      shell: pwsh
    # Install GTK2-Sharp (Linux)
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get install --yes gtk-sharp2="${{ inputs.gtkVersion }}"
      shell: pwsh
