name: Cache CPM
description: Caches CPM source for dependencies
inputs:
  cpmPath:
    description: "CPM source path to cache"
    required: false
    default: ${{ github.workspace }}/opt/cpm
runs:
  using: "composite"
  steps:
    # Cache CPM source deps
    - name: Set up CPM cache
      id: cache_cpm
      uses: actions/cache@v2
      with:
        path: ${{ inputs.cpmPath }}
        key: ${{ format('{0}-cpm-{1}', runner.os, hashFiles(format('{0}/**/', inputs.cpmPath)}}
        restore-keys: |
          ${{ runner.os }}-cpm-
