
name: NES

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CC65_PATH: ${{ github.workspace }}/opt/cc65
  FAMISTUDIO_PATH: ${{ github.workspace }}/opt/famistudio
  FAMISTUDIO_BIN: 3.2.2/FamiStudio322-LinuxAMD64.zip

jobs:
  build_nes_lib:
    name: NES Library Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cc65
      - uses: lukka/get-cmake@latest
      - name: Build NES Library
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'nes-library'
          buildPreset: 'nes-library'

  build_nes_example:
    name: NES Example Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cc65
      - uses: ./.github/actions/cache_famistudio
        with:
          fsBin: ${{ env.FAMISTUDIO_BIN }}
      - uses: lukka/get-cmake@latest
      - name: Build NES Example
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'nes'
          buildPreset: 'nes'
