
name: Windows MSVC

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FAMISTUDIO_BIN: 3.2.2/FamiStudio322-WinPortableExe.zip
  FAMISTUDIO_PATH: ${{ github.workspace }}/opt/famistudio

jobs:
  build_msvc_lib:
    name: MSVC Library Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
      - name: Build MSVC Library
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'msvc-library'
          buildPreset: 'msvc-library'

  build_msvc_example:
    name: MSVC Example Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/actions/cache_famistudio
        with:
          fsBin: ${{ env.FAMISTUDIO_BIN }}
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
      - name: Build MSVC Example
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'msvc'
          buildPreset: 'msvc'
