
name: NES

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CC65_PATH: ${{ github.workspace }}/opt/cc65
  FAMISTUDIO_PATH: ${{ github.workspace }}/opt/famistudio
  FAMISTUDIO_BIN: 3.2.2/FamiStudio322-LinuxAMD64.zip

jobs:
  build_nes_lib:
    name: NES Library Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cc65
      - name: Build NES Library
        run: |
          mkdir -p build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/cc65-toolchain.cmake -DCMAKE_PREFIX_PATH=${{ env.CC65_PATH }} -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCNES_BUILD_SINGLE=On ../
          make

  build_nes_example:
    name: NES Example Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cc65
      - uses: ./.github/actions/cache_famistudio
        with:
          fsBin: ${{ env.FAMISTUDIO_BIN }}
      - name: Build NES Example
        run: |
          mkdir -p example/build && cd example/build
          cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/cc65-toolchain.cmake -DCMAKE_PREFIX_PATH="${{ env.CC65_PATH }}" -DCMAKE_FRAMEWORK_PATH="${{ env.FAMISTUDIO_PATH }}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCNES_BUILD_SINGLE=On ../
          make
