
name: Linux

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FAMISTUDIO_BIN: 3.2.2/FamiStudio322-LinuxAMD64.zip
  FAMISTUDIO_PATH: ${{ github.workspace }}/opt/famistudio

jobs:
  build_linux_lib:
    name: Linux Library Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_sdl
      - name: Build PC Library
        run: |
          mkdir -p build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCNES_BUILD_SINGLE=On ../
          make -j2

  build_linux_example:
    name: Linux Example Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_sdl
      - uses: ./.github/actions/cache_famistudio
        with:
          fsBin: ${{ env.FAMISTUDIO_BIN }}
      - name: Build PC Example
        run: |
          mkdir -p example/build && cd example/build
          cmake -G "Unix Makefiles" -DCMAKE_FRAMEWORK_PATH="${{ env.FAMISTUDIO_PATH }}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCNES_BUILD_SINGLE=On ../
          make -j2
