
name: Linux

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CPM_PATH: ${{ github.workspace }}/opt/cpm
  FAMISTUDIO_BIN: 3.2.2/FamiStudio322-LinuxAMD64.zip
  FAMISTUDIO_PATH: ${{ github.workspace }}/opt/famistudio
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  build_linux_lib:
    name: Linux Library Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
      - name: Build Linux Library
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'native-library'

  build_linux_example:
    name: Linux Example Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
      - uses: ./.github/actions/cache_famistudio
        with:
          fsBin: ${{ env.FAMISTUDIO_BIN }}
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
      - name: Build Linux Example
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'native'
